---
- name: Install Apache and Upload my personal page
  hosts: all
  become: yes

  vars:
    source_folder: ../my-site
    dest_folder: /var/www/html

  tasks:
    - name: Do smth on ansible_master # delegate_to
      shell: echo This file was created on Ansible-master > /home/ec2-user/log.txt
      delegate_to: 127.0.0.1

    - block: #for RedHat
      - name: Install Apache for RedHat
        yum: name=httpd state=latest
      - name: Start Apache on RedHat
        service: name=httpd state=started enabled=yes
      when: ansible_os_family == "RedHat"

    - block: # for Debian
      - name: Install Apache for Debian
        apt: name=apache2 state=latest
      - name: Start Apache on Debian
        service: name=apache2 state=started enabled=yes
      when: ansible_os_family == "Debian"

    - name: Generate index.html # work with tamplate
      template: src={{ source_folder }}/index.j2 dest={{ dest_folder }}/index.html mode=0555
      notify:
        - Restart server on RedHat
        - Restart server on Debian
    - name: Copy my-site to the servers # copy static files by loop
      copy: src={{ source_folder }}/{{ item }} dest={{ dest_folder }} mode=0555
      loop:
        - lambo.png
        - ferrari.jpg
      notify:
        - Restart server on RedHat
        - Restart server on Debian


  handlers:
  - name: Restart server on RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
  - name: Restart server on Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
